### ISSUE TITLE
Documentation is missing for the support of TOML datetimes

### ISSUE THREAD

**Issue by stof** [vanodevium/toml#2]
The readme says "Supports TOML datetime formats". However, there is no explanation about what this support means.
Can a TOML datetime be decoded to a PHP `DateTimeImmutable` object ? And is `DateTimeImmutable` supported during encoding to be represented as a TOML datetime ?

**Comment by vanodevium** [comment]
@stof 

Hello! Thanx for question.

I'll try to describe with example:

> all TOML values are from specification

```php

$toml = <<<TOML

odt1 = 1979-05-27T07:32:00Z
odt2 = 1979-05-27T00:32:00-07:00
odt3 = 1979-05-27T00:32:00.999999-07:00
odt4 = 1979-05-27 07:32:00Z

ldt1 = 1979-05-27T07:32:00
ldt2 = 1979-05-27T00:32:00.999999

ld1 = 1979-05-27

lt1 = 07:32:00
lt2 = 00:32:00.999999

TOML;

dump(toml_decode($toml));

```

You will see

```php
{#84
  +"odt1": Devium\Toml\TomlDateTime {#29
    +dt: DateTime @296638320 {#30
      date: 1979-05-27 07:32:00.0 +00:00
    }
  }
  +"odt2": Devium\Toml\TomlDateTime {#36
    +dt: DateTime @296638320 {#37
      date: 1979-05-27 00:32:00.0 -07:00
    }
  }
  +"odt3": Devium\Toml\TomlDateTime {#43
    +dt: DateTime @296638320 {#44
      date: 1979-05-27 00:32:00.999999 -07:00
    }
  }
  +"odt4": Devium\Toml\TomlDateTime {#50
    +dt: DateTime @296638320 {#51
      date: 1979-05-27 07:32:00.0 +00:00
    }
  }
  +"ldt1": Devium\Toml\TomlLocalDateTime {#59
    +year: 1979
    +month: 5
    +day: 27
    +hour: 7
    +minute: 32
    +second: 0
    +millisecond: 0
  }
  +"ldt2": Devium\Toml\TomlLocalDateTime {#65
    +year: 1979
    +month: 5
    +day: 27
    +hour: 0
    +minute: 32
    +second: 0
    +millisecond: 999
  }
  +"ld1": Devium\Toml\TomlLocalDate {#63
    +year: 1979
    +month: 5
    +day: 27
  }
  +"lt1": Devium\Toml\TomlLocalTime {#74
    +millisecond: 0
    +hour: 7
    +minute: 32
    +second: 0
  }
  +"lt2": Devium\Toml\TomlLocalTime {#81
    +millisecond: 999
    +hour: 0
    +minute: 32
    +second: 0
  }
}

```

As you can see, every TOML date/time format is supported.

All these objects implement Stringable interface and properties are public. 

So you can transform values to any you want. 

> Unfortunately, if you use `toml_decode($toml, asArray: true)`, this behavior is radically different and only a textual representation is returned. But I am working on fixing this problem.

**Comment by stof** [comment]
Then I have a few suggestions:

1. The readme should explain this (probably not using a `dump` output though)
2. `TomDateTime` should probably use a `DateTimeImmutable instead of a mutable object
3. All the classes representing Toml datetime formats should be part of the public API instead of being `@internal` as it means they are expected to be used (and so should be covered by BC as well, but ideally only after doing the change in the previous suggestion)
4. it would be great if `toml_encode` could have support for `DateTimeInterface` by representing it as a toml offset datetime, even if they were not wrapped in a TomlDateTime object. This would make the usage a lot easier.

**Comment by vanodevium** [comment]
@stof 

I just wanted to apologize for these shortcomings.

This is my first such a complex library, I did the best I could.

That is why I am asking for reactions and recommendations on what and how best to do.

Thank you for the recommendations!

**Comment by vanodevium** [comment]
@stof 

Please advise if this documentation will be correct for the first iteration?
